kind: wasmer.io/App.v0
name: edge-multiplayer-games
app_id: da_RLmILtvUOlma
owner: wasmer
package: .
locality:
  regions:
    - fr-roub1
env:
  DAILY_GAME_WORK_ROOT: /data
  GITHUB_REPOSITORY: wasmerio/edge-multiplayer-games
  OPENAI_MODEL: gpt-6-astra
  JS_COMMAND: /bin/node
capabilities:
  memory:
    limit: 953.7 MiB
volumes:
  - name: daily-game-runs
    mount: /data
