kind: wasmer.io/App.v0
name: daily-2026-09-11
owner: wasmer
package: .
locality:
  regions:
  - fr-roub1
app_id: da_2l9IzteUY9dm
annotations:
  anybuild.run/config:
    commands:
      start: node src/server.js
    edgejs_enable: true
    edgejs_precompile: true
    name: out
    node_install_inputs:
    - package.json
    node_package_manager: npm
    node_package_name: daily-2026-09-11
    node_remove_native_binaries: true
    node_server: node
  anybuild.run/provider: node
  anybuild.run/version: 0.28.4
  wasmer.io/version: 7.4.1
