import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const base = process.argv[2] || 'http://localhost:8765';
const artifacts = process.env.ARTIFACTS_DIR || '/tmp/ring-rumble-artifacts';
await mkdir(artifacts, { recursive: true });
const browser = await chromium.launch({ headless: true, args: ['--no-sandbox', '--enable-unsafe-swiftshader', '--use-angle=swiftshader', '--disable-background-timer-throttling', '--disable-renderer-backgrounding'] });
const errors = [];
async function page(name, viewport={width:1440,height:1050}, touch=false) {
  const context = await browser.newContext({ viewport, hasTouch:touch });
  const p = await context.newPage();
  p.on('pageerror', error => errors.push(`${name}: ${error.message}`));
  await p.addInitScript(() => localStorage.setItem('rumble-name', 'Test fighter'));
  return p;
}
const wait = (p, fn) => p.waitForFunction(fn, null, { timeout: 20000 });
try {
  const health = await fetch(`${base}/healthz`);
  assert.equal(health.status,200); assert.equal(health.headers.get('access-control-allow-origin'),'*');
  assert.equal((await health.json()).ok,true);
  assert.equal((await fetch(`${base}/`)).status,200);
  assert.equal((await fetch(`${base}/ws`)).status,426);
  assert.equal((await fetch(`${base}/../etc/passwd`)).status,404);
  console.log('PASS server health, CORS, index, upgrade response, traversal');
  const host = await page('host');
  await host.goto(base);
  await wait(host,()=>!!window.rumble?.ws && window.rumble.ws.readyState===1);
  await host.screenshot({path:`${artifacts}/lobby-desktop.png`,fullPage:true});
  assert.equal(await host.locator('#graphics-error').isVisible(),false);
  await host.goto(`${base}/?create=1`);
  await host.locator('#invite').waitFor({state:'visible'});
  const invite=await host.locator('#invite-link').getAttribute('href');
  assert.match(invite,/\?room=[A-Z2-9]{4}$/);
  const guest=await page('guest');
  await guest.goto(invite);
  await guest.locator('#room-info').waitFor({state:'visible'});
  await wait(host,()=>[...window.rumble.peers.values()].some(p=>p.dc?.readyState==='open' && p.pc.connectionState==='connected'));
  await wait(guest,()=>[...window.rumble.peers.values()].some(p=>p.dc?.readyState==='open'));
  await host.locator('#start').click();
  await wait(guest,()=>window.rumble.snapshot?.f===0);
  const before=await host.evaluate(()=>window.rumble.game.fighters[1].x);
  await guest.keyboard.down('ArrowLeft');
  await wait(host,()=>window.rumble.inputs[1]===1);
  await wait(host,()=>window.rumble.game.fighters[1].x<2.5);
  await guest.keyboard.up('ArrowLeft');
  await wait(host,()=>window.rumble.inputs[1]===0);
  assert.ok((await host.evaluate(()=>window.rumble.game.fighters[1].x))<before);
  await guest.keyboard.down('j');
  await wait(host,()=>window.rumble.inputs[1]===16);
  await guest.evaluate(()=>window.dispatchEvent(new Event('blur')));
  await wait(host,()=>window.rumble.inputs[1]===0);
  await guest.keyboard.up('j');
  console.log('PASS auto-create, invite, auto-join, RTC connected/open, guest movement and blur release');
  // Arrange combat on the host; guest input travels over the real DataChannel.
  await host.evaluate(()=>{
    const g=window.rumble.game;
    Object.assign(g.fighters[0],{x:0,z:0,a:Math.PI/2,vx:0,vz:0,damage:0});
    Object.assign(g.fighters[1],{x:1.2,z:0,a:-Math.PI/2,vx:0,vz:0,damage:0});
  });
  await guest.keyboard.down('j');
  await wait(host,()=>window.rumble.game.fighters[0].damage>0);
  await guest.keyboard.up('j');
  await wait(guest,()=>window.rumble.snapshot.p[0][3]>0);
  await host.screenshot({path:`${artifacts}/match-desktop.png`,fullPage:true});
  const round=await host.evaluate(()=>window.rumble.game.round);
  await guest.keyboard.down('ArrowRight');
  await wait(host,()=>window.rumble.game.roundOver);
  await guest.keyboard.up('ArrowRight');
  await guest.locator('#banner').waitFor({state:'visible'});
  assert.equal(await host.evaluate(()=>window.rumble.game.scores.reduce((a,b)=>a+b,0)),1);
  await host.locator('#scene').click({position:{x:450,y:330}});
  await host.keyboard.press('Space');
  await wait(guest,()=>window.rumble.snapshot?.f>0);
  assert.equal(await host.evaluate(()=>window.rumble.game.round),round+1);
  console.log('PASS guest punch damages host, snapshot delivery, ring-out scoring, Space advances round');
  const late=await page('spectator'); await late.goto(invite, {waitUntil:'domcontentloaded',timeout:60000});
  await late.locator('#game').waitFor({state:'visible'});
  await wait(late,()=>!!window.rumble.snapshot);
  assert.match(await late.locator('#dash-status').innerText(),/Spectating/);
  assert.equal(await late.evaluate(()=>window.rumble.players.length),2);
  await host.evaluate(()=>{const g=window.rumble.game;g.freeze=0;g.scores[0]=4;g.fighters[1].x=30;});
  await wait(host,()=>window.rumble.game.roundOver);
  assert.equal(await host.evaluate(()=>window.rumble.game.winner(5)),0);
  await host.locator('#next').click();
  await wait(late,()=>window.rumble.players.length===3);
  assert.deepEqual(await host.evaluate(()=>window.rumble.game.scores),[0,0,0]);
  console.log('PASS late-join spectating and rematch roster/score reset');
  await guest.close();
  try { await wait(host,()=>window.rumble.game.disconnected.has(1)); } catch(e) {
    console.log(await host.evaluate(()=>({players:window.rumble.players, disconnected:[...window.rumble.game.disconnected],peers:[...window.rumble.peers].map(([id,p])=>[id,p.dc?.readyState,p.pc?.connectionState]),status:document.getElementById('status').textContent})));
    console.log(errors); throw e;
  }
  await late.close();
  await wait(host,()=>window.rumble.game.roundOver);
  console.log('PASS disconnected fighters eliminated');
  const mobile=await page('mobile',{width:390,height:844},true); await mobile.goto(base);
  await mobile.screenshot({path:`${artifacts}/lobby-mobile.png`,fullPage:true});
  await mobile.locator('#practice').click();
  await wait(mobile,()=>window.rumble.snapshot?.f===0);
  const punchBox = await mobile.locator('[data-input="16"]').boundingBox();
  await mobile.mouse.move(punchBox.x+punchBox.width/2,punchBox.y+punchBox.height/2);
  await mobile.mouse.down();
  await wait(mobile,()=>window.rumble.inputs[0]===16);
  await mobile.mouse.up();
  await wait(mobile,()=>window.rumble.inputs[0]===0);
  await mobile.screenshot({path:`${artifacts}/match-mobile.png`,fullPage:true});
  assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  console.log('PASS practice bot, mobile touch/release, no horizontal overflow');
  assert.deepEqual(errors,[]);
  console.log(`PASS no browser errors; screenshots: ${artifacts}`);
} finally { await browser.close(); }
