"""Clone, generate with Pi, validate, and optionally publish a draft pull request."""

import argparse
import base64
import datetime
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import tempfile
import urllib.error
from urllib.parse import urlencode, quote

from game_contract import assemble, CATALOG, REFERENCE, SPLIT, json_text
from github import GitHub, require
from processes import execute
from pi_runner import run_pi
from repository import regular_file, snapshot, assert_unchanged, stage_checked_files

EDITABLE = ("README.md", "public/game.js", "public/client.js", "public/index.html",
            "public/style.css", "test/scenarios.js", "game-entry.json")


def environment(temp):
    agent_home = temp / "home"
    agent_home.mkdir()
    env = {"PATH": "/bin:/usr/bin", "HOME": str(agent_home), "TMPDIR": str(temp),
           "GIT_CONFIG_NOSYSTEM": "1", "GIT_CONFIG_GLOBAL": "/dev/null",
           "GIT_PAGER": "cat", "PAGER": "cat",
           "GIT_TERMINAL_PROMPT": "0", "GIT_AUTHOR_NAME": "Wasmer game agent",
           "GIT_AUTHOR_EMAIL": "game-agent@users.noreply.github.com",
           "GIT_COMMITTER_NAME": "Wasmer game agent",
           "GIT_COMMITTER_EMAIL": "game-agent@users.noreply.github.com",
           "PI_CODING_AGENT_DIR": str(temp / "pi-state")}
    for name in ("GIT_SSL_CAINFO", "SSL_CERT_FILE", "SSL_CERT_DIR", "NODE_EXTRA_CA_CERTS"):
        if name in os.environ:
            env[name] = os.environ[name]
    return env


def git_environment(env, token):
    result = dict(env)
    if token:
        encoded = base64.b64encode(("x-access-token:" + token).encode()).decode()
        result.update(GIT_CONFIG_COUNT="3",
                      GIT_CONFIG_KEY_0="http.https://github.com/.extraheader",
                      GIT_CONFIG_VALUE_0="Authorization: Basic " + encoded,
                      GIT_CONFIG_KEY_1="http.followRedirects", GIT_CONFIG_VALUE_1="false",
                      GIT_CONFIG_KEY_2="credential.helper", GIT_CONFIG_VALUE_2="")
    return result


def existing_pr(gh, branch):
    owner = gh.root.split("/repos/", 1)[1].split("/", 1)[0]
    query = urlencode({"state": "all", "head": owner + ":" + branch, "base": "main"})
    pulls = gh.request("/pulls?" + query)
    return pulls[0] if pulls else None


def branch_exists(gh, branch):
    try:
        gh.request("/git/ref/heads/" + quote(branch, safe="/"))
        return True
    except urllib.error.HTTPError as error:
        if error.code != 404:
            raise
        error.close()
        return False


def ensure_pr(gh, branch, record):
    previous = existing_pr(gh, branch)
    if previous:
        return previous["html_url"]
    entry = record["entry"]
    body = (f"Adds **{entry['name']}**, a browser multiplayer game generated by Pi on Wasmer.\n\n"
            f"{entry['description']}\n\n"
            f"Source: `{record['slug']}/`. Base commit: `{record['base_sha']}`.\n\n"
            "Validation: JavaScript syntax, Game interface, and simulation scenarios passed.\n\n"
            "Browser gameplay, invite flow, and production deployment remain pending. "
            "After merging, run `./deploy.sh " + record['slug'] + " super` to publish the game and its catalog URL. "
            "This draft is not automatically merged.\n")
    try:
        result = gh.request("/pulls", {"title": f"Add {entry['name']} ({record['date']})",
                                      "head": branch, "base": "main", "body": body, "draft": True})
    except urllib.error.HTTPError as error:
        if error.code != 422:
            raise
        error.close()
        previous = existing_pr(gh, branch)
        if not previous:
            raise RuntimeError("GitHub rejected the pull request") from None
        return previous["html_url"]
    return result["html_url"]


def validate_paths(paths, allowed):
    unexpected = set(paths) - set(allowed)
    require(not unexpected, "Unexpected changed paths: " + ", ".join(sorted(unexpected)))


def read_candidate(work, slug, refs):
    game = work / slug
    for path in EDITABLE:
        file = game / path
        require(file.is_file() and not file.is_symlink() and file.resolve().is_relative_to(game.resolve())
                and not any(parent.is_symlink() for parent in file.parents if parent != work),
                "Missing or linked game file: " + path)
        require(file.stat().st_size <= 500000, "Game file exceeds size limit: " + path)
    entry = json.loads((game / "game-entry.json").read_text())
    prefix, separator, _ = refs["achtung/public/client.js"].partition(SPLIT)
    client = (game / "public/client.js").read_text()
    require(separator and client.startswith(prefix), "Client transport prefix changed")
    return {"name": entry["name"], "description": entry["description"],
            "readme": (game / "README.md").read_text(),
            "game_js": (game / "public/game.js").read_text(),
            "client_tail": client[len(prefix):], "index_html": (game / "public/index.html").read_text(),
            "style_css": (game / "public/style.css").read_text(),
            "scenarios_js": (game / "test/scenarios.js").read_text()}


def check_game(work, slug, env):
    game = work / slug
    for file in ("public/client.js", "public/game.js", "src/server.js", "test/scenarios.js"):
        execute(["/bin/node", "--check", file], game, env)
    output = execute(["/bin/node", str(Path(__file__).with_name("capture.mjs")),
                      "60", str(2 * 1024 * 1024), "/bin/node", "test/run.mjs"], game, env, timeout=65)
    require(bool(output.strip()), "Game checks produced no report")
    report = json.loads(output.splitlines()[-1])
    require(isinstance(report, dict) and report.get("ok") is True and report.get("interface") is True
            and isinstance(report.get("scenarios"), list) and 2 <= len(report["scenarios"]) <= 8
            and all(isinstance(name, str) and name for name in report["scenarios"])
            and len(set(report["scenarios"])) == len(report["scenarios"]), "Invalid scenario report")
    print("PASS game checks: " + json.dumps(report), flush=True)
    return report


def run(args):
    day = args.date
    require(re.fullmatch(r"\d{4}-\d{2}-\d{2}", day), "Invalid date")
    datetime.date.fromisoformat(day)
    require(re.fullmatch(r"[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+", args.repository), "Invalid GitHub repository")
    require(args.publish or args.output, "Preview requires --output /output and a host volume mounted there")
    preview = getattr(args, "from_preview", None)
    token = os.environ.get("GH_TOKEN", "")
    require(not args.publish or token, "--publish requires GH_TOKEN")
    slug, branch = "daily-" + day, "daily-game/" + day
    record_path = f"automation/daily-game/runs/{day}.json"
    gh = GitHub(args.repository, token) if args.publish else None
    recovery = False
    if gh:
        previous = existing_pr(gh, branch)
        if previous:
            print("PR already exists: " + previous["html_url"], flush=True)
            return
        recovery = branch_exists(gh, branch)
    reuse = recovery or bool(preview)
    require(reuse or os.environ.get("OPENAI_API_KEY"), "OPENAI_API_KEY is missing")
    print(f"Daily game {day}: {'publish draft PR' if args.publish else 'preview'}", flush=True)
    with tempfile.TemporaryDirectory(prefix="edge-daily-", ignore_cleanup_errors=True) as directory:
        temp = Path(directory)
        work = temp / "repository"
        env = environment(temp)
        auth_env = git_environment(env, token)
        def git(*words, cwd=work, network=False, raw=False):
            return execute(["/bin/git", "-c", "core.hooksPath=/dev/null", *words], cwd,
                           auth_env if network else env, timeout=120, strip=not raw)

        git("clone", "--single-branch", "--branch", branch if recovery else "main",
            "https://github.com/" + args.repository + ".git", str(work), cwd=temp, network=True)
        head = git("rev-parse", "HEAD")
        config = (work / ".git/config").read_bytes()
        if reuse:
            record = json.loads((work / record_path if recovery else Path(preview) / f"{slug}.json").read_text())
            require(record["date"] == day and record["slug"] == slug, "Existing branch is not a matching daily game")
            base = record["base_sha"]
            require(re.fullmatch(r"[0-9a-f]{40}", base), "Invalid base commit")
            if base != head:
                git("fetch", "origin", base, network=True)
            if not recovery:
                git("switch", "-c", branch, base)
                git("apply", "--index", "--", str((Path(preview) / f"{slug}.patch").resolve()))
                require(json.loads((work / record_path).read_text()) == record,
                        "Preview report differs from its patch")
        else:
            base = head
            if (work / slug).exists() or (work / record_path).exists():
                print("Game for this date is already on main", flush=True)
                return
        upload_filter = record.get("upload_filter", ".ignore") if reuse else ".wasmerignore"
        require(upload_filter in {".wasmerignore", ".ignore"}, "Invalid saved upload filter")
        refs = {path: git("show", base + ":" + path, raw=True) for path in REFERENCE}
        generated = json.loads(git("show", base + ":" + CATALOG, raw=True)) if git(
            "ls-tree", "--name-only", base, CATALOG) else []
        context = {"slug": slug, "files": refs,
                   "existing_games": json.loads(refs["public/games.json"]) + generated}
        if not reuse:
            git("switch", "-c", branch)
            scaffold = work / slug
            shutil.copytree(work / "achtung", scaffold, ignore=shutil.ignore_patterns(
                "node_modules", ".anybuild", ".shipit", ".git"))
            (scaffold / "test").mkdir(exist_ok=True)
            (scaffold / "test/run.mjs").write_text(Path(__file__).with_name("run.mjs").read_text())
            (scaffold / "game-entry.json").write_text(json_text({"name": "Choose a distinct name", "description": "Describe the game"}))
            baseline = {str(p.relative_to(work)): p.read_bytes() for p in scaffold.rglob("*") if p.is_file()}
            prompt = "INPUT\n" + json_text({"date": day, "game_directory": slug,
                "repository_instructions": refs["AGENTS.md"],
                "registration_contract": {
                    "catalog": "public/games.json", "upload_filter": upload_filter,
                    "metadata": "Write game-entry.json with name and description. The coordinator adds slug, players, source, and url: null to the root catalog and excludes the game directory from the root upload.",
                    "deployment": f"After merge, ./deploy.sh {slug} super deploys the game, records its actual Wasmer URL, and redeploys the superapp. Document this command in the game README; leave browser and deployment checks pending."},
                "editable_paths": [slug + "/" + path for path in EDITABLE],
                "existing_games": context["existing_games"],
                "client_boundary": "Keep public/client.js byte-for-byte unchanged before function applyMessage(msg) {. Adapt the renderer and input after that boundary to the existing host loop.",
                "checks": [f"cd {slug} && node --check public/client.js", f"cd {slug} && node test/run.mjs"],
                "scenario_contract": "Export scenarios: [{name, run(Game, assert)}]. Use at least two distinct scenarios; assert(condition, message)."})
            run_pi(work, {**env, "OPENAI_API_KEY": os.environ["OPENAI_API_KEY"]},
                   Path(__file__).with_name("daily-game-system.md"), prompt, args.model)
            require(git("rev-parse", "HEAD") == head, "Pi changed the Git commit")
            require((work / ".git/config").read_bytes() == config, "Pi changed Git configuration")
            changed = git("diff", "--name-only", "HEAD").splitlines()
            changed += git("ls-files", "--others", "--exclude-standard").splitlines()
            validate_paths(changed, baseline.keys() | {slug + "/" + p for p in EDITABLE})
            for path, content in baseline.items():
                if path not in {slug + "/" + p for p in EDITABLE}:
                    require((work / path).read_bytes() == content, "Pi changed a protected scaffold file: " + path)
        candidate = read_candidate(work, slug, refs)
        files, entry = assemble(candidate, context)
        if reuse:
            require(record["entry"] == entry, "Existing branch metadata differs from the game")
            # Validate committed files without replacing them before reopening the PR.
            for path, content in files.items():
                if path != "README.md":
                    require(regular_file(work, slug + "/" + path).read_text() == content, "Existing branch fails the game contract: " + path)
        else:
            for path, content in files.items():
                file = work / slug / path
                require(not file.is_symlink(), "Linked game file: " + path)
                file.parent.mkdir(parents=True, exist_ok=True)
                file.write_text(content)
        # Old saved previews remain recoverable; new runs always register in the superapp.
        registers_root = not reuse or record.get("root_catalog") == "public/games.json"
        root_catalog = json.loads(refs["public/games.json"]) + [{**entry, "url": None}]
        metadata_paths = {upload_filter, CATALOG, record_path}
        if registers_root:
            metadata_paths.add("public/games.json")
        allowed = {slug + "/" + path for path in files} | metadata_paths
        if reuse:
            validate_paths(git("diff", "--name-only", base, "HEAD").splitlines() if recovery else
                           git("diff", "--cached", "--name-only", base).splitlines(), allowed)
            require((work / upload_filter).read_text() == git("show", base + ":" + upload_filter, raw=True).rstrip() + "\n/" + slug + "/\n",
                    "Saved upload exclusions differ from the expected game entry")
            require(json.loads((work / CATALOG).read_text()) == generated + [entry], "Saved catalog differs from the expected game entry")
            if registers_root:
                require(json.loads(regular_file(work, "public/games.json").read_text()) == root_catalog,
                        "Saved root catalog differs from the expected game entry")
            if recovery:
                require(git("status", "--porcelain") == "", "Recovered branch has unexpected working changes")
        expected = {slug + "/" + path: regular_file(work, slug + "/" + path).read_bytes() for path in files}
        if reuse:
            expected.update({path: regular_file(work, path).read_bytes() for path in metadata_paths})
        before_checks = snapshot(work)
        validation_head = git("rev-parse", "HEAD")
        report = check_game(work, slug, env)
        assert_unchanged(work, before_checks)
        require(git("rev-parse", "HEAD") == validation_head, "Game checks changed the Git commit")
        require((work / ".git/config").read_bytes() == config, "Game checks changed Git configuration")
        if reuse:
            require(record["checks"] == report, "Saved check report differs from repeated checks")
            if recovery:
                require(git("status", "--porcelain") == "", "Game checks changed the recovered Git index")
        else:
            record = {"date": day, "slug": slug, "base_sha": base, "entry": entry,
                      "checks": report, "browser_checks": "pending", "deployment": "pending",
                      "root_catalog": "public/games.json", "upload_filter": upload_filter}
            ignore = work / upload_filter
            ignore_text = ignore.read_text().rstrip() + "\n/" + slug + "/\n"
            ignore.write_text(ignore_text)
            (work / CATALOG).parent.mkdir(parents=True, exist_ok=True)
            (work / CATALOG).write_text(json_text(generated + [entry]))
            regular_file(work, "public/games.json").write_text(json_text(root_catalog))
            (work / record_path).parent.mkdir(parents=True, exist_ok=True)
            (work / record_path).write_text(json_text(record))
            expected.update({upload_filter: ignore_text.encode(), CATALOG: json_text(generated + [entry]).encode(),
                             "public/games.json": json_text(root_catalog).encode(),
                             record_path: json_text(record).encode()})
            changed = git("diff", "--name-only", "HEAD").splitlines()
            changed += git("ls-files", "--others", "--exclude-standard").splitlines()
            # Remove unchanged copied extras so the new game contains only its contract files.
            for path in baseline.keys() - {slug + "/" + path for path in files}:
                (work / path).unlink()
            changed = [path for path in changed if path not in baseline.keys() - {slug + "/" + path for path in files}]
            validate_paths(changed, allowed)
        if not recovery:
            stage_checked_files(git, expected)
        if args.output:
            output = Path(args.output)
            output.mkdir(parents=True, exist_ok=True)
            (output / f"{slug}.patch").write_text(git("diff", "--binary", base, "HEAD", raw=True) if recovery else git("diff", "--cached", "--binary", base, raw=True))
            (output / f"{slug}.json").write_text(json_text(record))
            print("Saved preview to " + str(output), flush=True)
        if not args.publish:
            print("Preview passed; no remote branch or PR was created", flush=True)
            return
        if not recovery:
            git("commit", "-m", f"Add daily multiplayer game for {day}: {entry['name']}")
            # A concurrent writer rejects this ordinary push; never force an update.
            git("push", "origin", "HEAD:refs/heads/" + branch, network=True)
        print("PR: " + ensure_pr(gh, branch, record), flush=True)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--publish", action="store_true", help="Push a dated branch and open a draft PR")
    parser.add_argument("--output", help="Directory for the patch and check report")
    parser.add_argument("--from-preview", help="Reuse an existing preview directory and repeat validation without a model call")
    parser.add_argument("--repository", default=os.environ.get("GITHUB_REPOSITORY", "wasmerio/edge-multiplayer-games"))
    parser.add_argument("--model", default=os.environ.get("OPENAI_MODEL", "gpt-6-astra"))
    parser.add_argument("--date", default=datetime.datetime.now(datetime.timezone.utc).date().isoformat())
    run(parser.parse_args())


if __name__ == "__main__":
    try:
        main()
    except urllib.error.HTTPError as error:
        raise SystemExit(f"GitHub API failed: HTTP {error.code}. The branch may exist; rerun to recover its PR.") from None
    except (ValueError, RuntimeError, OSError, KeyError, subprocess.TimeoutExpired) as error:
        raise SystemExit(f"Daily game failed: {error}") from None
