"""Clone, generate with Pi, validate, and optionally publish a draft pull request."""

import argparse
import base64
import datetime
import json
import os
from pathlib import Path
import re
import subprocess
import urllib.error
from urllib.parse import urlencode, quote

from game_contract import (verify, editable, engine_version, engine_pin, json_text, AUTHORED, CATALOG,
                           CONFORMANCE, CONTEXT, ENGINE_PARAMS, FIXTURE, PLACEHOLDER,
                           PLACEHOLDER_DESCRIPTION, SCAFFOLD, SYNC)
from github import GitHub, require
from processes import execute
from pi_runner import run_pi
from repository import regular_file, snapshot, assert_unchanged, stage_checked_files
from workspace import run_workspace

RUNTIME = Path(__file__).resolve().parent


def environment(temp):
    agent_home = temp / "home"
    agent_home.mkdir()
    env = {"PATH": "/bin:/usr/bin", "HOME": str(agent_home), "TMPDIR": str(temp),
           "GIT_CONFIG_NOSYSTEM": "1", "GIT_CONFIG_GLOBAL": "/dev/null",
           "GIT_PAGER": "cat", "PAGER": "cat",
           "GIT_TERMINAL_PROMPT": "0", "GIT_AUTHOR_NAME": "Wasmer game agent",
           "GIT_AUTHOR_EMAIL": "game-agent@users.noreply.github.com",
           "GIT_COMMITTER_NAME": "Wasmer game agent",
           "GIT_COMMITTER_EMAIL": "game-agent@users.noreply.github.com",
           "PI_CODING_AGENT_DIR": str(temp / "pi-state")}
    for name in ("GIT_SSL_CAINFO", "SSL_CERT_FILE", "SSL_CERT_DIR", "NODE_EXTRA_CA_CERTS"):
        if name in os.environ:
            env[name] = os.environ[name]
    return env


def git_environment(env, token):
    result = dict(env)
    if token:
        encoded = base64.b64encode(("x-access-token:" + token).encode()).decode()
        result.update(GIT_CONFIG_COUNT="3",
                      GIT_CONFIG_KEY_0="http.https://github.com/.extraheader",
                      GIT_CONFIG_VALUE_0="Authorization: Basic " + encoded,
                      GIT_CONFIG_KEY_1="http.followRedirects", GIT_CONFIG_VALUE_1="false",
                      GIT_CONFIG_KEY_2="credential.helper", GIT_CONFIG_VALUE_2="")
    return result


def existing_pr(gh, branch):
    owner = gh.root.split("/repos/", 1)[1].split("/", 1)[0]
    query = urlencode({"state": "all", "head": owner + ":" + branch, "base": "main"})
    pulls = gh.request("/pulls?" + query)
    return pulls[0] if pulls else None


def branch_exists(gh, branch):
    try:
        gh.request("/git/ref/heads/" + quote(branch, safe="/"))
        return True
    except urllib.error.HTTPError as error:
        if error.code != 404:
            raise
        error.close()
        return False


def ensure_pr(gh, branch, record):
    previous = existing_pr(gh, branch)
    if previous:
        return previous["html_url"]
    entry = record["entry"]
    body = (f"Adds **{entry['name']}**, a browser multiplayer game generated by Pi on Wasmer.\n\n"
            f"{entry['description']}\n\n"
            f"Source: `{record['slug']}/`. Base commit: `{record['base_sha']}`. "
            f"Engine: `{record['checks']['engine']}`.\n\n"
            "Validation: JavaScript syntax, the engine's simulation shape, snapshot schema and budget, "
            "fixture replay, simulation tests, and the static conformance tier passed.\n\n"
            "The browser conformance tier, gameplay, invite flow, and production deployment remain pending. "
            "Run `node scripts/conformance.mjs " + record['slug'] + "` before merging. "
            "After merging, run `./deploy.sh " + record['slug'] + " super` to publish the game and its catalog URL. "
            "This draft is not automatically merged.\n")
    try:
        result = gh.request("/pulls", {"title": f"Add {entry['name']} ({record['date']})",
                                      "head": branch, "base": "main", "body": body, "draft": True})
    except urllib.error.HTTPError as error:
        if error.code != 422:
            raise
        error.close()
        previous = existing_pr(gh, branch)
        if not previous:
            raise RuntimeError("GitHub rejected the pull request") from None
        return previous["html_url"]
    return result["html_url"]


def validate_paths(paths, allowed, slug=None):
    unexpected = {path for path in paths if path not in allowed
                  and not (slug and path.startswith(slug + "/test/"))}
    require(not unexpected, "Unexpected changed paths: " + ", ".join(sorted(unexpected)))


def gate(reason, args, cwd, env, timeout=60):
    """Run one bounded check; a failure rejects the game under a named reason."""
    try:
        return execute(["/bin/node", str(RUNTIME / "capture.mjs"), str(timeout), str(2 * 1024 * 1024),
                        "/bin/node", *args], cwd, env, timeout=timeout + 5, failure_output=True)
    except RuntimeError as error:
        raise ValueError(f"{reason}: {error}") from None


def require_engine(work, env):
    """Fail before authoring when the scaffold, the gate, or the published engine is absent."""
    require((work / SCAFFOLD).is_file(), "Scaffold command is missing: node " + SCAFFOLD)
    require((work / CONFORMANCE).is_file(),
            "Conformance command is missing: node " + CONFORMANCE + "; the gate is never skipped")
    require((work / SYNC).is_file() and (work / ENGINE_PARAMS).is_file(),
            "Engine source is missing: " + ENGINE_PARAMS + " and " + SYNC)
    version = engine_version((work / ENGINE_PARAMS).read_text())
    require(re.fullmatch(r"[0-9]+\.[0-9]+\.[0-9]+", version), "Invalid engine version: " + version)
    unpublished = f"Engine version {version} is not published"
    require((work / "public/engine" / version).is_dir(), f"{unpublished}: public/engine/{version}/ is missing")
    gate(unpublished, [SYNC, "verify"], work, env)
    return version


def scaffold_game(work, temp, slug, env):
    """Run the repository's scaffold in a scratch checkout and return its files."""
    root = temp / "scaffold"
    (root / "engine").mkdir(parents=True)
    # The scaffold records its fixture through the engine, so the scratch checkout carries a copy.
    for module in sorted((work / "engine").glob("*.js")):
        (root / "engine" / module.name).write_bytes(module.read_bytes())
    gate("Scaffold command failed", [SCAFFOLD, slug, "--name", PLACEHOLDER, "--description", PLACEHOLDER_DESCRIPTION,
                                     "--root", str(root)], work, env)
    game = root / slug
    require(game.is_dir(), "Scaffold command wrote no game directory: node " + SCAFFOLD)
    files = {str(path.relative_to(game)): path.read_bytes() for path in sorted(game.rglob("*")) if path.is_file()}
    require(all(path in files for path in (*AUTHORED, FIXTURE, "src/server.js")),
            "Scaffold output is incomplete: node " + SCAFFOLD)
    return files


def read_candidate(work, slug, paths):
    game = work / slug
    require(game.is_dir() and not game.is_symlink(), "Missing game directory: " + slug)
    return {path: regular_file(work, slug + "/" + path).read_bytes() for path in sorted(paths)}


def conformance(work, slug, env):
    """Run the static tier; a missing, silent, or failing gate rejects the game."""
    def rows(text):
        try:
            result = json.loads(text[text.index("{"):text.rindex("}") + 1])
            return result if isinstance(result.get("rows"), list) and result["rows"] else None
        except (ValueError, AttributeError):
            return None
    try:
        output = gate("Conformance failed", [CONFORMANCE, slug, "--static", "--json"], work, env, timeout=120)
    except ValueError as error:
        result = rows(str(error))
        failed = [f"{row.get('id')}: {row.get('detail')}" for row in result["rows"] if row.get("status") != "pass"] if result else []
        raise ValueError("Conformance failed: " + "; ".join(failed)) if failed else error
    result = rows(output)
    require(result is not None, "Conformance produced no report; the gate is never skipped")
    failed = [str(row.get("id")) for row in result["rows"] if row.get("status") != "pass"]
    require(result.get("ok") is True and result.get("tier") == "static" and not failed,
            "Conformance did not pass every static row: " + ", ".join(failed))
    return {"tier": "static", "rows": [row["id"] for row in result["rows"]]}


def check_game(work, slug, env):
    game = work / slug
    tests = sorted("test/" + path.name for path in (game / "test").glob("*.test.mjs"))
    require(bool(tests), "Game has no test/*.test.mjs scenarios")
    modules = sorted("test/" + path.name for path in (game / "test").glob("*.mjs"))
    for file in ("public/client.js", "public/game.js", "src/server.js", *modules):
        gate("JavaScript syntax check failed: " + file, ["--check", file], game, env)
    output = gate("Game rejected", [str(RUNTIME / "check_game.mjs"), str(work), slug], work, env)
    require(bool(output.strip()), "Game checks produced no report")
    report = json.loads(output.splitlines()[-1])
    require(isinstance(report, dict) and report.get("ok") is True, "Invalid game check report")
    scenarios = 0
    for file in tests:
        summary = re.findall(r"^(?:ℹ|#) (tests|fail) (\d+)$", gate("Simulation tests failed: " + file, [file], game, env), re.M)
        counts = {key: int(value) for key, value in summary}
        require(counts.get("fail") == 0 and counts.get("tests", 0) > 0, "Simulation tests printed no passing summary: " + file)
        scenarios += counts["tests"]
    require(scenarios >= 2, "Require at least two simulation scenarios")
    report.update(tests=tests, scenarios=scenarios, conformance=conformance(work, slug, env))
    print("PASS game checks: " + json.dumps(report), flush=True)
    return report


def run(args):
    day = args.date
    require(re.fullmatch(r"\d{4}-\d{2}-\d{2}", day), "Invalid date")
    datetime.date.fromisoformat(day)
    require(re.fullmatch(r"[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+", args.repository), "Invalid GitHub repository")
    require(args.publish or args.output, "Preview requires --output /output and a host volume mounted there")
    preview = getattr(args, "from_preview", None)
    token = os.environ.get("GH_TOKEN", "")
    require(not args.publish or token, "--publish requires GH_TOKEN")
    slug, branch = "daily-" + day, "daily-game/" + day
    record_path = f"automation/daily-game/runs/{day}.json"
    gh = GitHub(args.repository, token) if args.publish else None
    recovery = False
    if gh:
        previous = existing_pr(gh, branch)
        if previous:
            print("PR already exists: " + previous["html_url"], flush=True)
            return
        recovery = branch_exists(gh, branch)
    reuse = recovery or bool(preview)
    require(reuse or os.environ.get("OPENAI_API_KEY"), "OPENAI_API_KEY is missing")
    print(f"Daily game {day}: {'publish draft PR' if args.publish else 'preview'}", flush=True)
    work_root = getattr(args, "work_root", None)
    with run_workspace(work_root, day) as temp:
        work = temp / "repository"
        env = environment(temp)
        auth_env = git_environment(env, token)
        def git(*words, cwd=work, network=False, raw=False):
            return execute(["/bin/git", "-c", "core.hooksPath=/dev/null", *words], cwd,
                           auth_env if network else env, timeout=120, strip=not raw)

        git("clone", "--single-branch", "--branch", branch if recovery else "main",
            "https://github.com/" + args.repository + ".git", str(work), cwd=temp, network=True)
        head = git("rev-parse", "HEAD")
        config = (work / ".git/config").read_bytes()
        if reuse:
            record = json.loads((work / record_path if recovery else Path(preview) / f"{slug}.json").read_text())
            require(record["date"] == day and record["slug"] == slug, "Existing branch is not a matching daily game")
            base = record["base_sha"]
            require(re.fullmatch(r"[0-9a-f]{40}", base), "Invalid base commit")
            if base != head:
                git("fetch", "origin", base, network=True)
            if not recovery:
                git("switch", "-c", branch, base)
                git("apply", "--index", "--", str((Path(preview) / f"{slug}.patch").resolve()))
                require(json.loads((work / record_path).read_text()) == record,
                        "Preview report differs from its patch")
        else:
            base = head
            if (work / slug).exists() or (work / record_path).exists():
                print("Game for this date is already on main", flush=True)
                return
        upload_filter = record.get("upload_filter", ".ignore") if reuse else ".wasmerignore"
        require(upload_filter in {".wasmerignore", ".ignore"}, "Invalid saved upload filter")
        refs = {path: git("show", base + ":" + path, raw=True) for path in CONTEXT}
        generated = json.loads(git("show", base + ":" + CATALOG, raw=True)) if git(
            "ls-tree", "--name-only", base, CATALOG) else []
        version = require_engine(work, env)
        scaffold = scaffold_game(work, temp, slug, env)
        context = {"slug": slug, "engine_version": version,
                   "existing_games": json.loads(refs["public/games.json"]) + generated}
        if not reuse:
            git("switch", "-c", branch)
            for path, content in scaffold.items():
                file = work / slug / path
                file.parent.mkdir(parents=True, exist_ok=True)
                file.write_bytes(content)
            prompt = "INPUT\n" + json_text({"date": day, "game_directory": slug,
                "repository_instructions": refs["AGENTS.md"],
                "engine": {"version": version, "pin": engine_pin(version),
                           "api": "engine/README.md", "reference_game": "achtung/",
                           "scaffold": f"The coordinator already ran node {SCAFFOLD} {slug}; do not run it again."},
                "registration_contract": {
                    "catalog": "public/games.json", "upload_filter": upload_filter,
                    "metadata": "Edit name, description, and players in game-entry.json. The coordinator adds url: null to the root catalog and excludes the game directory from the root upload.",
                    "deployment": f"After merge, ./deploy.sh {slug} super deploys the game, records its actual Wasmer URL, and redeploys the superapp. Document this command in the game README; leave browser and deployment checks pending."},
                "editable_paths": [slug + "/" + path for path in AUTHORED] + [slug + "/test/*"],
                "coordinator_owned_paths": sorted(slug + "/" + path for path in scaffold if not editable(path)),
                "existing_games": context["existing_games"],
                "record_fixture": f"cd {slug} && RECORD=1 node test/game.test.mjs",
                "checks": [f"cd {slug} && node test/game.test.mjs",
                           f"node {RUNTIME / 'check_game.mjs'} . {slug}",
                           f"node {CONFORMANCE} {slug} --static"]})
            run_pi(work, {**env, "OPENAI_API_KEY": os.environ["OPENAI_API_KEY"]},
                   RUNTIME / "daily-game-system.md", prompt, args.model)
            require(git("rev-parse", "HEAD") == head, "Pi changed the Git commit")
            require((work / ".git/config").read_bytes() == config, "Pi changed Git configuration")
            changed = git("diff", "--name-only", "HEAD").splitlines()
            changed += git("ls-files", "--others", "--exclude-standard").splitlines()
            validate_paths(changed, {slug + "/" + path for path in scaffold}, slug)
        listed = git("ls-files", "--cached", "--others", "--exclude-standard", "--", slug).splitlines()
        candidate = read_candidate(work, slug, {path.removeprefix(slug + "/") for path in listed
                                                if path.startswith(slug + "/")})
        files, entry = verify(candidate, scaffold, context)
        if reuse:
            require(record["entry"] == entry, "Existing branch metadata differs from the game")
            # Validate committed files without replacing them before reopening the PR.
            for path, content in files.items():
                require(candidate[path] == content, "Existing branch fails the game contract: " + path)
        else:
            for path in ("README.md", "game-entry.json"):
                (work / slug / path).write_bytes(files[path])
        # Old saved previews remain recoverable; new runs always register in the superapp.
        registers_root = not reuse or record.get("root_catalog") == "public/games.json"
        root_catalog = json.loads(refs["public/games.json"]) + [{**entry, "url": None}]
        metadata_paths = {upload_filter, CATALOG, record_path}
        if registers_root:
            metadata_paths.add("public/games.json")
        allowed = {slug + "/" + path for path in files} | metadata_paths
        if reuse:
            validate_paths(git("diff", "--name-only", base, "HEAD").splitlines() if recovery else
                           git("diff", "--cached", "--name-only", base).splitlines(), allowed)
            require((work / upload_filter).read_text() == git("show", base + ":" + upload_filter, raw=True).rstrip() + "\n/" + slug + "/\n",
                    "Saved upload exclusions differ from the expected game entry")
            require(json.loads((work / CATALOG).read_text()) == generated + [entry], "Saved catalog differs from the expected game entry")
            if registers_root:
                require(json.loads(regular_file(work, "public/games.json").read_text()) == root_catalog,
                        "Saved root catalog differs from the expected game entry")
            if recovery:
                require(git("status", "--porcelain") == "", "Recovered branch has unexpected working changes")
        expected = {slug + "/" + path: content for path, content in files.items()}
        if reuse:
            expected.update({path: regular_file(work, path).read_bytes() for path in metadata_paths})
        before_checks = snapshot(work)
        validation_head = git("rev-parse", "HEAD")
        report = check_game(work, slug, env)
        assert_unchanged(work, before_checks)
        require(git("rev-parse", "HEAD") == validation_head, "Game checks changed the Git commit")
        require((work / ".git/config").read_bytes() == config, "Game checks changed Git configuration")
        if reuse:
            require(record["checks"] == report, "Saved check report differs from repeated checks")
            if recovery:
                require(git("status", "--porcelain") == "", "Game checks changed the recovered Git index")
        else:
            record = {"date": day, "slug": slug, "base_sha": base, "entry": entry,
                      "checks": report, "browser_checks": "pending", "deployment": "pending",
                      "root_catalog": "public/games.json", "upload_filter": upload_filter}
            ignore = work / upload_filter
            ignore_text = ignore.read_text().rstrip() + "\n/" + slug + "/\n"
            ignore.write_text(ignore_text)
            (work / CATALOG).parent.mkdir(parents=True, exist_ok=True)
            (work / CATALOG).write_text(json_text(generated + [entry]))
            regular_file(work, "public/games.json").write_text(json_text(root_catalog))
            (work / record_path).parent.mkdir(parents=True, exist_ok=True)
            (work / record_path).write_text(json_text(record))
            expected.update({upload_filter: ignore_text.encode(), CATALOG: json_text(generated + [entry]).encode(),
                             "public/games.json": json_text(root_catalog).encode(),
                             record_path: json_text(record).encode()})
            changed = git("diff", "--name-only", "HEAD").splitlines()
            changed += git("ls-files", "--others", "--exclude-standard").splitlines()
            validate_paths(changed, allowed)
        if not recovery:
            stage_checked_files(git, expected)
        output_path = args.output or (temp / "artifacts" if work_root else None)
        if output_path:
            output = Path(output_path)
            output.mkdir(parents=True, exist_ok=True)
            (output / f"{slug}.patch").write_text(git("diff", "--binary", base, "HEAD", raw=True) if recovery else git("diff", "--cached", "--binary", base, raw=True))
            (output / f"{slug}.json").write_text(json_text(record))
            print("Saved preview to " + str(output), flush=True)
        if not args.publish:
            print("Preview passed; no remote branch or PR was created", flush=True)
            return
        if not recovery:
            git("commit", "-m", f"Add daily multiplayer game for {day}: {entry['name']}")
            # A concurrent writer rejects this ordinary push; never force an update.
            git("push", "origin", "HEAD:refs/heads/" + branch, network=True)
        pr_url = ensure_pr(gh, branch, record)
        if work_root:
            (temp / "pr.json").write_text(json_text({"url": pr_url, "branch": branch}))
        print("PR: " + pr_url, flush=True)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--publish", action="store_true", help="Push a dated branch and open a draft PR")
    parser.add_argument("--output", help="Directory for the patch and check report")
    parser.add_argument("--work-root", default=os.environ.get("DAILY_GAME_WORK_ROOT"),
                        help="Mounted directory for retained run files, including failed attempts")
    parser.add_argument("--from-preview", help="Reuse an existing preview directory and repeat validation without a model call")
    parser.add_argument("--repository", default=os.environ.get("GITHUB_REPOSITORY", "wasmerio/edge-multiplayer-games"))
    parser.add_argument("--model", default=os.environ.get("OPENAI_MODEL", "gpt-6-astra"))
    parser.add_argument("--date", default=datetime.datetime.now(datetime.timezone.utc).date().isoformat())
    run(parser.parse_args())


if __name__ == "__main__":
    try:
        main()
    except urllib.error.HTTPError as error:
        raise SystemExit(f"GitHub API failed: HTTP {error.code}. The branch may exist; rerun to recover its PR.") from None
    except (ValueError, RuntimeError, OSError, KeyError, subprocess.TimeoutExpired) as error:
        raise SystemExit(f"Daily game failed: {error}") from None
